CREATE TABLE users(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, first_name TEXT NOT NULL, second_name TEXT NOT NULL, age INT NOT NULL);
INSERT INTO users (first_name, second_name, age)
SELECT
    CASE
        WHEN (random() * 100)::int % 2 = 0 THEN 'John'
        WHEN (random() * 100)::int % 3 = 0 THEN 'Alice'
        WHEN (random() * 100)::int % 5 = 0 THEN 'Bob'
        WHEN (random() * 100)::int % 7 = 0 THEN 'Emily'
        ELSE 'Michael'
END,
    CASE
        WHEN (random() * 100)::int % 2 = 0 THEN 'Smith'
        WHEN (random() * 100)::int % 3 = 0 THEN 'Johnson'
        WHEN (random() * 100)::int % 5 = 0 THEN 'Brown'
        WHEN (random() * 100)::int % 7 = 0 THEN 'Davis'
        ELSE 'Wilson'
END,
    (18 + (random() * 50)::int)
FROM generate_series(1, 100);