CREATE TABLE IF NOT EXISTS orders
(
    id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                INT            NOT NULL,
    order_date             TIMESTAMP      NOT NULL,
    order_status           VARCHAR(255)   NOT NULL,
    order_amount           INT            NOT NULL,
    product_id             INT            NOT NULL,
    product_quantity       INT            NOT NULL,
    product_price          NUMERIC(10, 2) NOT NULL,
    total_price_on_order   NUMERIC(10, 2) NOT NULL,
    total_price_on_product NUMERIC(10, 2) NOT NULL
);